### ISSUE TITLE
아이디 분실시 처리

### ISSUE THREAD

**Issue by Wits15730** [snucse/snucse#111]
안녕하세요? 20학번 학생입니다. 1학년 초부터 스누씨에 로그인하려 했으나 실수로 아이디를 잊어버렸는데, 비밀번호 찾기는 있어도 아이디 찾기가 없는 것 같습니다. 그래서 지금가지 로그인에 성공해지 못했습니다...

비밀번호 확인 말고도 아이디 확인이 있으면 좋을 것 같습니다

감사합니다

**Comment by seojangho** [comment]
안녕하세요. 이메일 주소를 contact@bacchus.snucse.org 에 알려주시면 조치해드리겠습니다.
말씀드린 내용은 고려하겠습니다. 감사합니다.

**Comment by seojangho** [comment]
https://github.com/bacchus-snu/id/issues/136 로 이동.
