### ISSUE TITLE
마이그레이션 된 태그들에 대해서 prefix 검색이 불가능한 버그

### ISSUE THREAD

**Issue by Leeingnyo** [snucse/snucse#48]
태그 추가를 하기 위해서 태그 첫 글자를 검색했는데, 스누씨3가 되면서 새로 등록되어진 태그를 제외하고는 나타나지 않습니다.

'아' 를 검색하면 '아'로 시작하는 많은 태그들(ex. '아니 정말', '아니 이 사람들이', '아이돌 마스터')이 나타나야 하는데, 하나도 나타나지 않고 있습니다. 반면, '♪'를 검색하면, 제가 '♪자유' 태그를 스누씨3가 되고나서 추가한 적이 있기 때문에 나타납니다.

**Comment by bryanj** [comment]
데이터 보정해서 해결했습니다.
