### ISSUE TITLE
태그 페이지 로딩 중 띄우기

### ISSUE THREAD

**Issue by Leeingnyo** [snucse/snucse#50]
로딩 중일 때도 not found 라는 문구가 뜹니다.
그리고 not found 라는 문구도 고쳐야겠어요.

**Comment by tirr-c** [comment]
#2

**Comment by Leeingnyo** [comment]
sorry... 그럼 이 이슈는 not found 문구를 고치는 이슈로

**Comment by Leeingnyo** [comment]
not found 문구 고치는 이슈는 따로 팔게요
