### ISSUE TITLE
활동 페이지에서 태그 이름이 undefined로 보이는 문제

### ISSUE THREAD

**Issue by gangwon** [snucse/snucse#53]
Activity 페이지의 ArticleTag 아이템에서 태그 이름이 항상 undefined로 보입니다.

(테스트는 해 보지 않았지만) ProfileTag, ImageTag에서도 똑같은 일이 생길 수도 있습니다.

**Comment by Leeingnyo** [comment]
(스크린샷)

이것 말씀이신가요? 음... 더 자세한 상황을 들어봐야 할 것 같습니다

**Comment by gangwon** [comment]
![image](https://cloud.githubusercontent.com/assets/2162884/23589871/05538a3c-0219-11e7-81f4-f7bda1bbf0f4.png)

위 스크린샷과 같이 보입니다. (https://www.snucse.org/activities) 참고로 대분류로 필터링을 하면 태그 이름이 제대로 보이고 그래서 위에서는 재현에 실패하신 것 같습니다.

그리고, 실제 서비스 중인 스누씨 스크린샷을 여기에 올려도 되나요? 일단 저는 불필요한 내용은 가리기는 했습니다만...

**Comment by Leeingnyo** [comment]
앗... 제가 생각이 짧았습니다ㅠㅠ 일단 지웠고, 스크린샷에 대한 것과 버그에 대해서 알아보겠습니다.

**Comment by Leeingnyo** [comment]
filterType이 명시되지 않은 경우, activity type이 ArticleTag 임에도 tag 정보가 포함되지 않고 있습니다. 확인해주세요. @operatz

**Comment by bryanj** [comment]
이슈 파악하고 수정했습니다. 다음 배포 때 반영 예정입니다.

**Comment by bryanj** [comment]
https://github.com/snucse/snucse-api/releases/tag/3.1.3 배포로 해결되었습니다
