### ISSUE TITLE
Remove stale branches

### ISSUE THREAD

**Issue by simnalamburt** [snucse/snucse#85]
Currently, there are 19 branches in this project and I doubt if they're all really needed.

[![image](https://cloud.githubusercontent.com/assets/4435445/24337253/02ca4a1c-12d6-11e7-937a-2efa71bf6bb6.png)](https://github.com/snucse/snucse/branches/all)

Let's remove `authentication`, `agpl-3.0`, `add-change-password-box`, and `taginfo-loading-placeholder` branches. And since this project is not a close-sourced project anymore, we can freely fork this project without paying a fee. Why do not you just push the branch for pull requests into your own fork repository instead of this project?

**Comment by simnalamburt** [comment]
May I delete those branches?

**Comment by bryanj** [comment]
Thanks for pointing out. I just removed `authentication` branch which was last updated by me.

**Comment by bryanj** [comment]
@Leeingnyo @pps789 현재 브랜치 중 머지가 완료된 브랜치는 지워도 될 것 같습니다. 임의로 지우는 것보다 마지막 커밋한 사람이 확인 후 지우는 게 나을 것 같으니 확인해주세요.

**Comment by tirr-c** [comment]
앋 제가 그냥 지워버렸네요...

---

앞으로 자기 작업물은 먼저 포크해서 작업한 뒤 업스트림에 PR 날리는 게 좋을 것 같네요.

**Comment by simnalamburt** [comment]
Closing this issue since there's no more stale branch.
