### ISSUE TITLE
태그 삭제를 해도 클라이언트에 남아있음

### ISSUE THREAD

**Issue by Leeingnyo** [snucse/snucse#87]
지워야 합니다.

또 이미 다른 누군가가 삭제해서 없는 태그도 지워져야 합니다.

**Comment by pps789** [comment]
태그 삭제 시 서버에서 다시 태그 목록을 가져와 보여주는데, 이 때 직전에 삭제한 태그도 목록에 포함되어 클라이언트에 남아있게 됩니다.

**Comment by Leeingnyo** [comment]
@operatz 위 댓글 참고하셔서 작업부탁드립니다.

**Comment by bryanj** [comment]
@Leeingnyo 서버에서 해당 문제 수정하여 개발서버에 배포했습니다. 확인해주세요. 문제 없을 경우 서비스 서버 배포 뒤 이슈 닫으면 될 것 같습니다.

**Comment by Leeingnyo** [comment]
@operatz 확인했습니다. 문제 없습니다.
